#!/usr/bin/env bash
# ============================================================================
# Baidu AI Studio (Feijiang) one-shot environment setup.
# Target: V100 16 GB notebook, PaddlePaddle 3.x image (Python 3.10+).
#
# The image's conda site-packages is read-only for the notebook user, so
# everything is installed into a dedicated uv venv under /home/aistudio/work.
# Paddle is left untouched and the notebook kernel is not modified.
#
#   bash setup_baidu_studio.sh [REPO_URL]
# ============================================================================
set -euo pipefail

REPO_URL="${1:-https://github.com/haotemans/DiffSynth-Studio.git}"
BRANCH="${BRANCH:-v100-t4-16gb}"
WORK="${WORK:-/home/aistudio/work}"
VENV="${VENV:-${WORK}/venv-diffsynth}"
PY="$(command -v python3 || command -v python)"

echo "[1/6] python: $($PY --version) at $PY"

# Keep the uv cache on the same writable volume as the venv, otherwise uv can
# fail with cross-device hardlink errors on managed images.
export UV_CACHE_DIR="${UV_CACHE_DIR:-${WORK}/.uv-cache}"
# Route every uv resolution (including build-isolation deps) through the mirror.
export UV_DEFAULT_INDEX="${UV_DEFAULT_INDEX:-https://mirrors.aliyun.com/pypi/simple/}"
export UV_INDEX_URL="${UV_INDEX_URL:-$UV_DEFAULT_INDEX}"

# --- uv wrapper (console script may be missing from PATH) -------------------
USER_BASE="$("$PY" -m site --user-base 2>/dev/null || echo "$HOME/.local")"
export PATH="$HOME/.local/bin:${USER_BASE}/bin:$PATH"
if ! command -v uv >/dev/null 2>&1 && ! "$PY" -m uv --version >/dev/null 2>&1; then
  echo "[2/6] installing uv ..."
  "$PY" -m pip install uv -i https://mirrors.aliyun.com/pypi/simple/ \
    || "$PY" -m pip install --user uv -i https://mirrors.aliyun.com/pypi/simple/
fi
if command -v uv >/dev/null 2>&1; then
  UV() { uv "$@"; }
  echo "[2/6] uv: $(uv --version)"
else
  UV() { "$PY" -m uv "$@"; }
  echo "[2/6] uv via python -m: $("$PY" -m uv --version 2>&1)"
fi

# --- dedicated venv (system site-packages is read-only on managed images) ---
echo "[3/6] venv at $VENV"
mkdir -p "$WORK" "$UV_CACHE_DIR" "$WORK/hf_home" "$WORK/modelscope_cache"

# Persisted environment, sourced automatically by Qwen-Image-2.1-16GB.sh so a
# fresh notebook session (or a restart) reuses the same venv, caches and models.
cat > "$WORK/diffsynth_env.sh" <<ENVEOF
# generated by setup_baidu_studio.sh - do not edit
export VENV="\${VENV:-${VENV}}"
export UV_CACHE_DIR="\${UV_CACHE_DIR:-${UV_CACHE_DIR}}"
export HF_HOME="${WORK}/hf_home"
export HUGGINGFACE_HUB_CACHE="${WORK}/hf_home/hub"
export MODELSCOPE_CACHE="${WORK}/modelscope_cache"
export XDG_CACHE_HOME="${WORK}/cache"
export TORCH_HOME="${WORK}/cache/torch"
export DIFFSYNTH_DISABLE_FLEX_ATTN=1
ENVEOF
mkdir -p "$WORK/cache" "$WORK/cache/torch"
. "$WORK/diffsynth_env.sh"
if [ ! -x "$VENV/bin/python" ]; then
  # uv does not need pip inside the venv, so --without-pip is a safe fallback.
  UV venv "$VENV" --python "$PY" \
    || "$PY" -m venv "$VENV" \
    || "$PY" -m venv --without-pip "$VENV"
fi
VPY="$VENV/bin/python"
if [ ! -x "$VPY" ]; then
  echo "ERROR: could not create a writable venv at $VENV" >&2
  echo "       set VENV=/some/writable/path and re-run." >&2
  exit 1
fi

# --- torch (Aliyun mirror, CUDA build picked from the driver) ---------------
CUDA_VER="$(nvidia-smi 2>/dev/null | grep -oP 'CUDA Version: \K[0-9]+\.[0-9]+' || echo 11.8)"
if "$VPY" -c "import sys; sys.exit(0 if float('$CUDA_VER') >= 12.1 else 1)"; then
  CUDA_TAG="cu121"
else
  CUDA_TAG="cu118"
fi
echo "[4/6] driver CUDA $CUDA_VER -> torch $CUDA_TAG from mirrors.aliyun.com"
UV pip install --python "$VPY" \
  "torch==2.5.1+${CUDA_TAG}" "torchvision==0.20.1+${CUDA_TAG}" \
  --find-links "https://mirrors.aliyun.com/pytorch-wheels/${CUDA_TAG}/" \
  --index-url "https://mirrors.aliyun.com/pypi/simple/"

# --- training deps ----------------------------------------------------------
echo "[5/6] training dependencies ..."
UV pip install --python "$VPY" \
  "bitsandbytes>=0.45.0" "accelerate>=0.34.0" "peft>=0.12.0" \
  "transformers>=4.45.0" sentencepiece protobuf safetensors \
  modelscope ftfy pandas einops "imageio[ffmpeg]" "numpy<2" \
  --index-url "https://mirrors.aliyun.com/pypi/simple/" \
  --extra-index-url "https://pypi.org/simple"

# --- repo -------------------------------------------------------------------
echo "[6/6] cloning ${REPO_URL} (${BRANCH}) ..."
cd "$WORK"
if [ ! -d DiffSynth-Studio ]; then
  git clone -b "$BRANCH" "$REPO_URL" || git clone "$REPO_URL"
fi
cd DiffSynth-Studio
git checkout "$BRANCH" 2>/dev/null || true
git pull --ff-only 2>/dev/null || true
UV pip install --python "$VPY" -e . --no-deps \
  --index-url "https://mirrors.aliyun.com/pypi/simple/"

"$VPY" - <<'EOF'
import torch
print(f"torch {torch.__version__} | cuda {torch.version.cuda} | {torch.cuda.get_device_name(0)}")
print(f"VRAM {torch.cuda.get_device_properties(0).total_memory / 1024**3:.1f} GB")
import bitsandbytes, peft, accelerate, transformers
print(f"bitsandbytes {bitsandbytes.__version__} | peft {peft.__version__} | accelerate {accelerate.__version__} | transformers {transformers.__version__}")
EOF
echo "=== done. The notebook kernel is NOT modified; training runs from the venv."
echo "    cd $WORK/DiffSynth-Studio && bash examples/qwen_image_21/model_training/special/low_vram_training/Qwen-Image-2.1-16GB.sh"
echo "    (interactive use: source $VENV/bin/activate)"
